name: Fetch NHK RSS Feed

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 mins

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch NHK RSS feeds
        run: |
          current_month=$(date +'%Y%m')
          current_week=$(date +'%Y%m_%W') # 1-51
          day_offset=$(( 7 - current_day_of_week ))
          current_time=$(date +'%Y%m%d_%H%M')
          folder_name="xml-NHK_${current_week}"
          mkdir -p $folder_name
          sleep 3
          curl -o "${folder_name}/nhk_main_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat0.xml
          sleep 3
          curl -o "${folder_name}/nhk_domestic_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat1.xml
          sleep 3
          curl -o "${folder_name}/nhk_science_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat3.xml
          sleep 3
          curl -o "${folder_name}/nhk_politics_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat4.xml
          sleep 3
          curl -o "${folder_name}/nhk_economics_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat5.xml)
          sleep 3
          curl -o "${folder_name}/nhk_world_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat6.xml
          sleep 3
          curl -o "${folder_name}/nhk_sports_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat7.xml
          sleep 3
          curl -o "${folder_name}/nhk_bunka_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat2.xml
          sleep 3
          curl -o "${folder_name}/nhk_live_${current_time}.xml" https://www.nhk.or.jp//www.nhk.or.jp/rss/news/cat-live.xml


      - name: Set Git Config
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
        working-directory: ${{ github.workspace }}
        
      - name: Commit and push XML files
        run: |
          git add .
          git commit -m "Update - $(date +'%Y-%m-%d')"
          git push
        working-directory: ${{ github.workspace }}

